[workspace]
members = [
    "crates/carta-format",
    "crates/carta-core",
]
exclude = ["experiments/keyboard-events"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"

[workspace.dependencies]
chrono = { version = "0.4.42", default-features = false, features = ["clock", "serde", "std"] }
pulldown-cmark = { version = "0.13.4", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["arbitrary_precision"] }
tempfile = "3.23.0"
thiserror = "2.0.17"
unicode-casefold = "0.2.0"
unicode-normalization = "0.1.24"
uuid = { version = "1.18.1", features = ["serde", "v7"] }
