[package]
name = "carta-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
carta-core = { path = "../carta-core" }
carta-publish = { path = "../carta-publish" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
pulldown-cmark.workspace = true
unicode-width = "0.2.0"

[dev-dependencies]
tempfile.workspace = true
